import Link from 'next/link';
import { notFound } from 'next/navigation';
import { fetchGrantsGovDetail } from '@/lib/providers/grantsGov';
import { getFederalAwardHistory } from '@/lib/intelligence/usaspending';
function money(value?:number){if(value===undefined)return'Not listed';return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value)}
export default async function OpportunityPage({params}:{params:Promise<{id:string}>}){
 const{id}=await params;if(!id.startsWith('grants-'))notFound();let item;try{item=await fetchGrantsGovDetail(id.replace(/^grants-/,''))}catch{notFound()}
 const history=await getFederalAwardHistory((item.assistanceListings||[]).map(x=>x.number));
 return <main className="detailShell"><Link className="backLink" href="/">← Back to search</Link><article className="detailCard"><div className="badges"><span className="sourceBadge">{item.source}</span>{item.sourceTier&&<span className="softBadge">{item.sourceTier}</span>}{item.status&&<span className="softBadge">{item.status}</span>}</div><h1 className="detailTitle">{item.title}</h1><p className="detailAgency">{item.funder}{item.number?` · ${item.number}`:''}</p>
 <div className="detailGrid"><div><small>Award floor</small><strong>{money(item.amountMin)}</strong></div><div><small>Award ceiling</small><strong>{money(item.amountMax)}</strong></div><div><small>Deadline</small><strong>{item.deadline||'Not listed'}</strong></div><div><small>Cost sharing</small><strong>{item.costSharing===undefined?'Not listed':item.costSharing?'Yes':'No'}</strong></div></div>
 {(item.totalFunding!==undefined||item.expectedAwards!==undefined)&&<div className="detailGrid"><div><small>Total program funding</small><strong>{money(item.totalFunding)}</strong></div><div><small>Expected awards</small><strong>{item.expectedAwards?.toLocaleString()||'Not listed'}</strong></div><div><small>Posted</small><strong>{item.postedDate||'Not listed'}</strong></div><div><small>Mapped data</small><strong>{item.dataCompleteness??0}% complete</strong></div></div>}
 {item.assistanceListings?.length?<section className="detailSection"><h2>Assistance listings</h2><div className="tagList">{item.assistanceListings.map(x=><span key={x.number}>{x.number}{x.title?` · ${x.title}`:''}</span>)}</div></section>:null}
 {history&&history.sampleCount>0?<section className="historyPanel"><div><span className="eyebrow">Historical context</span><h2>What similar federal awards have looked like</h2><p>USAspending records for Assistance Listing {history.programNumbers.join(', ')} from roughly the last five years. This is historical context—not the official award range for this opportunity.</p></div><div className="historyStats"><div><small>Median sampled award</small><strong>{money(history.medianAward)}</strong></div><div><small>Sampled awards</small><strong>{history.sampleCount.toLocaleString()}</strong></div><div><small>Sample range</small><strong>{money(history.minAward)} – {money(history.maxAward)}</strong></div></div>{history.recentAwards.length>0&&<div className="awardExamples">{history.recentAwards.slice(0,3).map((a,i)=><div key={`${a.awardId}-${i}`}><strong>{a.recipient}</strong><span>{money(a.amount)}{a.agency?` · ${a.agency}`:''}</span></div>)}</div>}</section>:null}
 <section className="detailSection"><h2>About this opportunity</h2><p>{item.description}</p></section>{item.eligibility.length>0&&<section className="detailSection"><h2>Who can apply</h2><div className="tagList">{item.eligibility.map(x=><span key={x}>{x}</span>)}</div></section>}{(item.fundingInstruments?.length||item.categories?.length)?<section className="detailSection"><h2>Funding details</h2><p>{[...(item.fundingInstruments||[]),...(item.categories||[])].join(' · ')}</p></section>:null}{(item.contactName||item.contactEmail||item.contactPhone)&&<section className="detailSection"><h2>Agency contact</h2><p>{item.contactName}{item.contactEmail?` · ${item.contactEmail}`:''}{item.contactPhone?` · ${item.contactPhone}`:''}</p></section>}<div className="detailActions"><a className="buttonLink" href={item.url} target="_blank" rel="noreferrer">View official listing ↗</a></div></article></main>
}
