import { completeness, FundingProvider, Opportunity, ProviderResult } from '@/lib/opportunity';

const URL='https://epa.illinois.gov/topics/grants-loans.html';
function clean(v=''){return v.replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim()}
function hash(input:string){let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)}
export const illinoisProvider:FundingProvider={name:'Illinois EPA Funding',async search(query,limit):Promise<ProviderResult>{try{
  const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);
  const res=await fetch(URL,{headers:{'User-Agent':'OpenFunding/0.4 public-funding-discovery'},signal:controller.signal,redirect:'follow',next:{revalidate:900}}).finally(()=>clearTimeout(timer));
  if(!res.ok)throw new Error(`HTTP ${res.status}`);const html=await res.text();const text=clean(html);const marker=text.toLowerCase().indexOf('current funding opportunities');const slice=marker>=0?text.slice(marker,marker+7000):text.slice(0,7000);const q=query.toLowerCase();const checked=new Date().toISOString();
  const chunks=slice.split(/(?=[A-Z][A-Za-z0-9&()'’\- ]{8,80}(?:Grant|Program|Fund|Funding))/).slice(1);const rows:Opportunity[]=[];
  for(const chunk of chunks){const title=(chunk.match(/^(.{8,140}?(?:Grant Program|Program|Grant|Fund))/i)?.[1]||'').trim();if(!title)continue;const desc=chunk.slice(title.length,Math.min(chunk.length,650)).trim();if(q&&!`${title} ${desc}`.toLowerCase().includes(q))continue;const dateMatch=desc.match(/(?:until|through|by)\s+([A-Z][a-z]+\s+\d{1,2},\s+\d{4})/i);const rolling=/until funding is expended|until funding has been expended|rolling/i.test(desc);const item:Opportunity={id:`il-${hash(title)}`,providerId:title,source:'Illinois EPA Funding',sourceKind:'web',sourceTier:'state',title,funder:'Illinois Environmental Protection Agency',status:'Open',category:'Environment & Water',categories:['State','Environment & Water'],eligibility:[],deadline:rolling?'Rolling':dateMatch?.[1],deadlineType:rolling?'rolling':dateMatch?'fixed':'unknown',geography:'Illinois',url:URL,description:desc||'Illinois state funding opportunity.',lastChecked:checked,detailAvailable:false};item.dataCompleteness=completeness(item);rows.push(item);if(rows.length>=limit)break;}
  if(!rows.length)throw new Error('Page reachable, but no current opportunities were parsed');return{provider:'Illinois EPA Funding',opportunities:rows,total:rows.length,note:'Official Illinois state agency funding page'};
}catch(error){return{provider:'Illinois EPA Funding',opportunities:[],error:error instanceof Error?error.message:String(error)}}}};
