import type { FundingProvider, Opportunity, ProviderResult } from '@/lib/opportunity';
import { absoluteUrl, cleanHtml, fetchHtml, finish, hash, normalizeDate } from './webSource';
const URL='https://egrants.gov.texas.gov/fundingopp'; const ORIGIN='https://egrants.gov.texas.gov';
export const texasProvider:FundingProvider={name:'Texas eGrants',async search(query,limit):Promise<ProviderResult>{try{
 const html=await fetchHtml(URL);const q=query.toLowerCase();const checked=new Date().toISOString();const rows:Opportunity[]=[];const seen=new Set<string>();
 const links=[...html.matchAll(/<a\b[^>]*href=["']([^"']*fundingopp[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi)];
 for(const m of links){const title=cleanHtml(m[2]);if(title.length<8||/funding opportunities|active opportunities|archived opportunities/i.test(title))continue;const href=absoluteUrl(m[1],ORIGIN);if(seen.has(href))continue;seen.add(href);const around=cleanHtml(html.slice(Math.max(0,(m.index||0)-700),Math.min(html.length,(m.index||0)+2400)));if(q&&!`${title} ${around}`.toLowerCase().includes(q))continue;const due=around.match(/Due Date\s*(\d{1,2}\/\d{1,2}\/\d{4})/i)?.[1];const avail=around.match(/Available\s*(\d{1,2}\/\d{1,2}\/\d{4})/i)?.[1];const purpose=around.match(/Purpose:\s*(.{30,700}?)(?=Name:|Available|Due Date|$)/i)?.[1]||around;rows.push(finish({id:`tx-${hash(href+title)}`,providerId:href,source:'Texas eGrants',sourceKind:'web',sourceTier:'state',title,funder:'Texas Office of the Governor',status:'Available',category:'State',categories:['State'],opportunityType:/request for proposals?|\bRFP\b/i.test(around)?'Request for Proposal':'Grant',fundingInstruments:['Grant'],eligibility:[],openDate:normalizeDate(avail),postedDate:normalizeDate(avail),deadline:normalizeDate(due),deadlineType:due?'fixed':'unknown',geography:'Texas',url:href,description:purpose.slice(0,520),lastChecked:checked,detailAvailable:false}));if(rows.length>=limit)break}
 return{provider:'Texas eGrants',opportunities:rows,total:rows.length,note:'Official Texas Office of the Governor active funding opportunities'};
}catch(error){return{provider:'Texas eGrants',opportunities:[],error:error instanceof Error?error.message:String(error)}}}};
