import Link from 'next/link';
import type { Opportunity } from '@/lib/opportunity';
export type FundingResult=Opportunity;
export type DisplayField='award'|'eligibility'|'deadline'|'geography'|'posted'|'type'|'costShare'|'expectedAwards'|'completeness'|'sourceTier';
function date(value?:string){if(!value)return undefined;if(value.toLowerCase()==='rolling')return'Rolling';const d=new Date(value);return Number.isNaN(d.valueOf())?value:d.toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function money(value?:number){if(value===undefined)return undefined;if(value>=1e6)return`$${(value/1e6).toFixed(value%1e6?1:0)}M`;if(value>=1e3)return`$${Math.round(value/1e3)}K`;return`$${value.toLocaleString()}`}
function award(item:Opportunity){const min=money(item.amountMin),max=money(item.amountMax);if(min&&max)return`${min} – ${max}`;if(max)return`Up to ${max}`;if(min)return`From ${min}`;if(item.estimatedAmountMin||item.estimatedAmountMax){const a=money(item.estimatedAmountMin),b=money(item.estimatedAmountMax);return`Est. ${a||''}${a&&b?' – ':''}${b||''}`.trim()}return undefined}
function trim(v:string,l=220){return v.length>l?`${v.slice(0,l-1).trim()}…`:v}
export default function FundingCard({item,fields,expanded,onToggle,saved,onSave}:{item:FundingResult;fields:DisplayField[];expanded:boolean;onToggle:()=>void;saved:boolean;onSave:()=>void}){
 const quick=[fields.includes('award')&&award(item)?['Award',award(item)!]:null,fields.includes('deadline')&&(item.deadline||item.deadlineType==='rolling')?['Deadline',item.deadlineType==='rolling'?'Rolling':date(item.deadline)!]:null,fields.includes('eligibility')&&item.eligibility.length?['Eligibility',trim(item.eligibility.slice(0,2).join(', '),62)]:null,fields.includes('geography')&&item.geography?['Geography',item.geography]:null].filter(Boolean) as [string,string][];
 return <article className="card"><div className="cardTop"><div className="cardMain"><div className="badges"><span className="sourceBadge">{item.source}</span>{item.sourceTier&&<span className="softBadge">{item.sourceTier}</span>}{item.category&&<span className="softBadge">{item.category}</span>}{item.topicTags?.slice(0,2).map(tag=><span className="softBadge topicBadge" key={tag}>{tag}</span>)}{item.status&&<span className="softBadge">{item.status}</span>}</div><h3>{item.title}</h3><p className="agency">{item.funder}{item.number?` · ${item.number}`:''}</p></div><div className="cardSide"><button className={saved?'saveButton saved':'saveButton'} onClick={onSave} type="button" aria-pressed={saved} aria-label={saved?'Remove saved opportunity':'Save opportunity'}>{saved?'♥':'♡'}</button>{fields.includes('deadline')&&<span className="deadline">{item.deadlineType==='rolling'?'Rolling':item.deadline?`Due ${date(item.deadline)}`:'Deadline not listed'}</span>}</div></div>
 {quick.length>0&&<div className="quickFacts">{quick.map(([l,v])=><div key={l}><small>{l}</small><strong>{v}</strong></div>)}</div>}<p className="description">{trim(item.description)}</p>
 {item.estimateBasis&&<div className="estimateNote">Estimated funding shown from {item.estimateBasis.replace(/-/g,' ')} · {item.estimateConfidence||'unknown'} confidence</div>}
 {expanded&&<><div className="expandedFacts">{fields.includes('posted')&&<div><small>Posted</small><strong>{date(item.postedDate)||'Not listed'}</strong></div>}{fields.includes('type')&&<div><small>Funding type</small><strong>{item.opportunityType||item.fundingInstruments?.join(', ')||'Not listed'}</strong></div>}{fields.includes('costShare')&&<div><small>Cost share</small><strong>{item.costSharing===undefined?'Not listed':item.costSharing?'Required':'Not required'}</strong></div>}{fields.includes('expectedAwards')&&<div><small>Expected awards</small><strong>{item.expectedAwards?.toLocaleString()||'Not listed'}</strong></div>}{fields.includes('completeness')&&<div><small>Mapped data</small><strong>{item.dataCompleteness??0}% complete</strong></div>}{fields.includes('sourceTier')&&<div><small>Funding level</small><strong>{item.sourceTier||'Not listed'}</strong></div>}<div><small>Source format</small><strong>{item.sourceKind.toUpperCase()}</strong></div>{item.firstSeen&&<div><small>First seen</small><strong>{date(item.firstSeen)||item.firstSeen}</strong></div>}</div>{((item.populations?.length||0)>0||(item.fundingUses?.length||0)>0)&&<section className="intelligenceBlock" aria-label="OpenFunding Intelligence"><div className="intelligenceHead"><strong>OpenFunding Intelligence</strong><span>{item.intelligenceMethod==='ai'?'AI-assisted':item.intelligenceMethod==='hybrid'?'Hybrid':'Transparent rules'} · {item.intelligenceVersion||'v1'}</span></div>{item.populations?.length?<div className="intelRow"><small>Population</small><div>{item.populations.map(x=><span key={x}>{x}</span>)}</div></div>:null}{item.fundingUses?.length?<div className="intelRow"><small>Funding use</small><div>{item.fundingUses.map(x=><span key={x}>{x}</span>)}</div></div>:null}<p>These are OpenFunding-derived discovery tags, not official funder classifications.</p></section>}</>}
 <div className="cardActions"><button className="textButton" type="button" onClick={onToggle} aria-expanded={expanded}>{expanded?'Hide quick details ↑':'More quick details ↓'}</button>{item.detailAvailable?<Link className="primaryLink" href={`/opportunity/${item.id}`}>Full details →</Link>:null}{item.url?<a href={item.url} target="_blank" rel="noreferrer">Official source ↗</a>:null}</div></article>
}
